### ISSUE TITLE
✨ Every page should have unique meta info

### ISSUE THREAD

**Issue by bartwr** [thehaguetech/thehaguetech-site#15]
Whenever we share anything from THT website on social media, the title & image that is shown on the post preview is always the same.

For example If you share https://www.thehaguetech.com/ this is the post preview:

![image](https://user-images.githubusercontent.com/899234/72112568-35185f00-333e-11ea-8048-3f8e0fbbf1a1.png)

The image for the home page is fine, but the title & short description should be different. For example:

> The Hague Tech
> 
> The largest tech community in The Hague offering co-working space, event space, meeting space, labs...

That should be an easy fix but the main problem is elsewhere. Now if I share another page e.g. https://www.thehaguetech.com/meetings-events-labs which is the meetings event and lab space page I get the exact same preview as above.

This extends to our Contentful pages as well. So if I share an event from THT website e.g. https://www.thehaguetech.com/events/2020-01-17/empathic-leadership I get the same

Or if I share a story about our current vacancy https://www.thehaguetech.com/stories/vacancy-for-part-time-community-and-events-organizers I get the same preview. title and image...the preview is always the same...

**Comment by bartwr** [comment]
Reply to feature request above:

At the moment every page has the same Facebook preview title, image & description. You can find these over here: https://github.com/thehaguetech/thehaguetech-site/blob/master/pages/_app.js#L44

We can easily update the meta info, and make it specific for every page.

Suggestions:

- [ ] For the homepage, update title & description to Ali's suggestions above
- [ ] For other pages, set a meta title, description + image per page
- [ ] For [events](https://www.thehaguetech.com/events/2020-01-14/from-0-to-80k-social-media-marketing-with-bcklads) & stories, take title, subtitle as description & image automatically as meta data

#TODO

**Comment by bartwr** [comment]
All meta data is updated based on [Page Social Previews for THT Website](https://docs.google.com/document/d/1iYnSMB4HplSseDRZss8Ibm7HD2-2ArAFM5FgISY-8SM/edit?ts=5e189f0c):

- [Index](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.thehaguetech.com%2F)
- [Community](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.thehaguetech.com%2Fcommunity)
- [Co-working](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.thehaguetech.com%2Fcoworking)
- [International Business](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.thehaguetech.com%2Finternational-business)
- [Co-creation](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.thehaguetech.com%2Fco-creation)
- [Events](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.thehaguetech.com%2Fevents)
- [Stories & News](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.thehaguetech.com%2Fstories)
- [Pricing](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.thehaguetech.com%2Fpricing)
- [Contact](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.thehaguetech.com%2Fcontact)

![image](https://user-images.githubusercontent.com/899234/72274892-478be480-362d-11ea-9e62-b25d901dd598.png)

**Comment by bartwr** [comment]
To make story & event previes working, I need to make server side rendering work on Heroku.

- [Example Event](https://www.thehaguetech.com/events/2020-01-14/from-0-to-80k-social-media-marketing-with-bcklads)
- [Example of Story](https://www.thehaguetech.com/stories/vacancy-for-part-time-community-and-events-organizers)

**Comment by bartwr** [comment]
Closed. Fixed by https://github.com/thehaguetech/thehaguetech-site/commit/7d721e8189c42e7fde900b9d15780a8e69680510

____

Still open:
- [Add meta info to Story & Event pages](https://github.com/thehaguetech/thehaguetech-site/issues/16)
